# Generated by Django 3.1.7 on 2022-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squads',
            name='club_id',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
