# Generated by Django 3.1.7 on 2022-05-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0004_auto_20220511_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squads',
            name='club_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
