# Generated by Django 3.1.7 on 2022-05-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0005_auto_20220511_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squads',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
