# Generated by Django 3.1.7 on 2022-05-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0006_auto_20220511_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squads',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
