# Generated by Django 3.1.7 on 2022-05-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0008_auto_20220511_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squads',
            name='club_id',
        ),
        migrations.AlterField(
            model_name='squads',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
