# Generated by Django 3.1.7 on 2022-05-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_clubs_jogadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='estadio_foto',
        ),
    ]
