# Generated by Django 4.0.4 on 2022-05-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_players', '0002_auto_20220506_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
