# Generated by Django 3.1.7 on 2022-05-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_players', '0003_alter_best_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_player',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
