# Generated by Django 3.1.7 on 2022-05-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(max_length=200)),
                ('foto', models.CharField(max_length=200)),
                ('nome', models.TextField(default=' ', null=True)),
                ('pontos', models.TextField(default=' ', null=True)),
                ('jogos', models.TextField(default=' ', null=True)),
                ('vitorias', models.TextField(default=' ', null=True)),
                ('empates', models.TextField(default=' ', null=True)),
                ('derrotas', models.TextField(default=' ', null=True)),
                ('saldo', models.TextField(default=' ', null=True)),
            ],
        ),
    ]
