# Generated by Django 4.0.4 on 2022-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golden_Boot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('club', models.TextField(default=' ', null=True)),
                ('goals', models.TextField(default=' ', null=True)),
                ('image', models.TextField(default=' ', null=True)),
                ('country', models.TextField(default=' ', null=True)),
                ('matches', models.TextField(default=' ', null=True)),
            ],
        ),
    ]
