# Generated by Django 4.0.4 on 2022-05-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden_boot', '0002_auto_20220506_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golden_boot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
