# Generated by Django 4.0.4 on 2022-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('data', models.TextField(default=' ', null=True)),
                ('pais', models.TextField(default=' ', null=True)),
                ('idade', models.TextField(default=' ', null=True)),
                ('altura', models.TextField(default=' ', null=True)),
                ('clube', models.TextField(default=' ', null=True)),
                ('valor', models.TextField(default=' ', null=True)),
                ('numerodacamisa', models.TextField(default=' ', null=True)),
                ('jogos', models.TextField(default=' ', null=True)),
                ('gols', models.TextField(default=' ', null=True)),
                ('assistencia', models.TextField(default=' ', null=True)),
                ('image', models.TextField(default=' ', null=True)),
            ],
        ),
    ]
